### ISSUE TITLE
Why error remote error: tls: handshake failure?

### ISSUE THREAD

**Issue by zhoulg** [domainr/epp#37]
When I run cmd/epp.go to connect remote epp server ,show me the error
Loading CA certificate from cacert.pem
Loading certificate cert.pem and key key.pem
Connecting to epp.registrysystem.net:700
Establishing TLS connection
remote error: tls: handshake failure
EXITING
exit status 1

 // Set up TLS
        cfg := &tls.Config{
                PreferServerCipherSuites:true,
                CipherSuites: []uint16{
                        tls.TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,
                        tls.TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,
                },
                MinVersion:         tls.VersionTLS11,
                MaxVersion:         tls.VersionTLS11,
                InsecureSkipVerify:true,
                ServerName: host,
        }

go version go1.10.3 linux/amd64

Thanks a lot!

**Comment by zhoulg** [comment]
go run epp.go  -addr epp.registrysystem.net:700 -u ****-BI -p *****pass -ca cacert.pem -cert cert.pem -key key.pem -v 1

**Comment by ydnar** [comment]
Can you open a TLS connection to that server using that client certificate?
