### ISSUE TITLE
Fail when sending command

### ISSUE THREAD

**Issue by RiRe** [domainr/epp#45]
We successfully connected EPP server but fail when sending manual command (domain registration). We tried several variants using the underlying TLS connection and even modifying the library. We are stuck with the same error every time

Example code:

```go
func euStart() {
	dialer := &net.Dialer{
		LocalAddr: &net.TCPAddr{
			IP:   net.ParseIP("xx.xx.xx.xxx"), 
			Port: 0}}

	eppConn, err := tls.DialWithDialer(dialer, "tcp", "xxx:700", nil)
	if err != nil {
		fmt.Println("EPP dial error: ", err)
		os.Exit(3)
	}

	eppClient, err := epp.NewConn(eppConn)
	if err != nil {
		fmt.Println("EPP init error: ", err)
		os.Exit(3)
	}

	err = eppClient.Login("xxx", "xxx", "")
	if err != nil {
		fmt.Println("EPP login error: ", err)
		os.Exit(3)
	}

	domain := "test6890.eu"
	xml := "<?xml version=\"1.0\" encoding=\"UTF-8\"?><epp xmlns=\"urn:ietf:params:xml:ns:epp-1.0\"><command><create><domain:create xmlns:domain=\"urn:ietf:params:xml:ns:domain-1.0\"><domain:name>" + domain + "</domain:name><domain:registrant>xxx</domain:registrant><domain:contact type=\"billing\">xxx</domain:contact><domain:contact type=\"tech\">xxx</domain:contact><domain:authInfo><domain:pw> </domain:pw></domain:authInfo></domain:create></create></command></epp>"
	eppClient.Conn.Write([]byte(xml + "\n"))
}
```

We get a runtime error at time of writing to connection (last line):

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x61b62b]

goroutine 1 [running]:
main.euReg(0x7ffc6eaef84d, 0xb)
        /home/debian/xxx.go:186 +0xdb
main.xxx(0x7ffc6eaef84d, 0xb)
        /home/debian/xxx.go:57 +0x3ae
main.main()
        /home/debian/xxx.go:31 +0xd2
```

Any ideas? Thanks

**Comment by ydnar** [comment]
@RiRe hi there. The current version of this package does not support the EPP `<create>` command, so I can’t really offer help here.

The main issue with your code is that it’s attempting to write XML directly to the underlying connection without the EPP payload size header. Your code essentially bypasses the package’s I/O and puts the connection into an indeterminate state. See `(*Conn).writeDataUnit` in conn.go for more information.

If you want to fork this package to add support for the EPP `<create>` command, I’m happy to review a pull request.

For what it’s worth, iet was probably a mistake to export the underlying `net.Conn` in the `epp.Conn` struct. It shouldn’t be accessed directly once this package assumes control.
