### ISSUE TITLE
Add Support for Verisign

### ISSUE THREAD

**Issue by wbond** [domainr/epp#9]
To query Verisign EPP servers, you need to use the namestoreExt (https://www.verisign.com/assets/namestore-extension.pdf?inc=www.verisigninc.com) and provide a subProduct from the following:

 - .com: `dotCOM`
 - .bz: `dotBZ`
 - .cc: `dotCC`
 - .tv: `dotTV`
 - .com: `dotCOM`
 - .net: `dotNET`
 - .edu: `dotEDU`
 - .jobs: `dotJOBS`

**Comment by case** [comment]
@wbond heard back from Verisign:

> Could you please confirm that the environment you are submitting the commands for the new g-TLD's is Namestore, instead of Core?

> The Core environment includes .COM and .NET, while Namestore would be the environment for the new g-TLD's. Additionally, unlike .COM & .NET, we do not accept the subProduct with "dot" in it, so if specifying the subProduct for .CAREER, it should only be "CAREER", not "dotCAREER".

> Below is sample XML code for the .JOBS TLD.

```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<epp xmlns="urn:ietf:params:xml:ns:epp-1.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="urn:ietf:params:xml:ns:epp-1.0 epp-1.0.xsd">
<command xmlns="urn:ietf:params:xml:ns:epp-1.0">
  <check>
    <domain:check
      xmlns:domain="urn:ietf:params:xml:ns:domain-1.0"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="urn:ietf:params:xml:ns:domain-1.0 domain-1.0.xsd"
    >
      <domain:name>EXAMPLE.JOBS</domain:name>
    </domain:check>
  </check>
  <extension>
    <namestoreExt:namestoreExt
      xmlns:namestoreExt="http://www.verisign-grs.com/epp/namestoreExt-1.1"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.verisign-grs.com/epp/namestoreExt-1.1 namestoreExt-1.1.xsd"
    >
      <namestoreExt:subProduct>dotJOBS</namestoreExt:subProduct>
    </namestoreExt:namestoreExt>
  </extension>
  <clTRID>ABC-77189-XYZ</clTRID>
</command>
</epp>
```

**Comment by case** [comment]
This is solved.
